name: "Multi event pipeline"

on:
    push:
        branches:
            - master

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master branch"
              run: echo "Running on master branch"