name: "Multi event pipeline"

on:
    push:
        branches:
            - master
            - test
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master/test branch"
              run: echo "Running on master/test branch"
            - name: "Print date"
              run: date
    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"
    on-workflow-master:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - name: "Working on workflow dispatch pipeline"
              run: echo "Working on workflow dispatch pipeline/workflow"